# Use Node.js LTS version
FROM node:18-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY backend/package*.json ./

RUN npm install

# Bundle app source
COPY backend/ .

# Expose port
EXPOSE 3000

# Start the server
CMD ["node", "server.js"]
