name: Frontend Build and Push

on:
  push:
    branches:
      - main
    paths:
      - 'src/frontend/**'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    environment:
      name: "dev"

    steps:
      # Step 1: Check out code
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Step 2: Login to Azure Container Registry  
      - name: 'Build and push image'
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.ACR_NAME }}.azurecr.io
          username: ${{ vars.ACR_ARM_CLIENT_ID }}
          password: ${{ secrets.ACR_ARM_CLIENT_SECRET }}
      - run: |
          docker build -f src/Dockerfile.frontend -t ${{ vars.ACR_NAME }}.azurecr.io/book-with-me-frontend:${{ github.sha }} .
          docker push ${{ vars.ACR_NAME }}.azurecr.io/book-with-me-frontend:${{ github.sha }}


